global:
  scrape_interval: 5s
  #scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:

  # - job_name: otel-collector
  #   honor_timestamps: true
  #   scrape_interval: 5s
  #   #scrape_timeout: 1s
  #   metrics_path: /metrics
  #   scheme: http
  #   follow_redirects: true
  #   static_configs:
  #     - targets:
  #         - collector:8889
  #         - collector:8888
  #       labels:
  #         group: otel-collector

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'collector'
    static_configs:
      - targets: ['collector:8888']
  
  - job_name: 'collector-exporter'
    static_configs:
      - targets: ['collector:8889']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'mssql-exporter'
    static_configs:
      - targets: ['mssql-exporter:4000']
  
  #- job_name: 'aspnetcore-exporter'
  #  static_configs:
  #    - targets: ['192.168.1.110:5286']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
  
  - job_name: 'keycloak'
    metrics_path: /metrics
    static_configs:
      - targets: ['keycloak:8080']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Use the http_2xx module for probing
    static_configs:
      - targets:
          - http://keycloak:8080/health/live
          - http://keycloak:8080/health/ready
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'rabbitmq-exporter'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'elasticsearch-exporter'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
